### ISSUE TITLE
Binary int serialization is endianess-dependent

### ISSUE THREAD

**Issue by krojew** [bitbouncer/kspp#13]
binary_serdes::encode()/decode() do not take endianess into account and always use current platform one. This can cause incompatibilities when other services are on different platforms.

**Comment by skarlsson** [comment]
the binary encoding was implemented more as a testing tool before avro serialization was done. It was never intended to work platform independent. Being binary and without schema was not inteded for large systems. Do you think it would be valuable for anything non trivial?

**Comment by krojew** [comment]
Since binary_serdes is a part of the library and it's used in the examples, I think we can assume people will use it, and possibly experience problems.
