### ISSUE TITLE
Need clarification 

### ISSUE THREAD

**Issue by pvssrikanth** [bitbouncer/kspp#31]
Dear Sir,

I have installed docker file on ubuntu linux and following message is appearing. 

dpkg-query: no path found matching pattern *librdkafka.so.1*
dpkg-query: no path found matching pattern *librocksdb.so.5.18*
dpkg-query: no path found matching pattern *libthrift-0.12.0.so*
Removing intermediate container 9d07d030d941
 ---> 82a49ef44181
[Warning] One or more build-args [IMAGE_TAG] were not consumed
Successfully built 82a49ef44181
Successfully tagged kspp-build-ubuntu:latest
~/srik/stream/kspp/docker-ubuntu
af2b83faeef06c49b22ac455aa5acdc6e756596bdc403b69eb683715187d1860

IS IT RUNNING FINE ?

If so could you please help me how to test it by sending email to srikanthpvs@gmail.com

Thanks in advance

**Comment by skarlsson** [comment]
The warnings can be ignored - it's the stuff that there are no packages for (ie built by 3rd party part) 
73cfccc fixes docker build problems (ie missing flags for build step)

**Comment by pvssrikanth** [comment]
Dear Sir,
Please guide how to test this please 

small application to visualize 

Thanks

**Comment by pvssrikanth** [comment]
Dear Sir,
Please guide how to test this please

small application to visualize

Thanks
